DEFAULT_TIME_DISPLACEMENT = 0
DEFAULT_WIDTH = "320"
DEFAULT_BITRATE_KBPS = "300"
DEFAULT_FRAME_RATE = "24"
DEFAULT_SEGMENT_DURATION = "1"
DEFAULT_FRAGMENT_DURATION = "0.1"
DEFAULT_INTRA_INTERVAL = "24"
DEFAULT_TARGET_LATENCY = "0.5"
DEFAULT_SERVER_SIDE_REPRESENTATION_SWITCHING = False
DEFAULT_SAVE_STATS = False

